name: version_bump

on:
  workflow_dispatch:
    inputs:
      releaseKind:
        description: 'Kind of version bump'
        default: 'minor'
        type: choice
        options:
        - patch
        - minor
        - major
        required: true

jobs:
  build:
    name: version bump
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1

      # TODO: add later
      # - name: Run version bump
      #   run: |
      #     git remote add upstream https://github.com/jonnydgreen/nifty-lil-tricks-testing
      #     ./_tools/release/01_bump_version.ts --${{github.event.inputs.releaseKind}}

      # TODO: add later
      # - name: Create PR
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.JONNYDGREEN_BOT_PAT }}
      #     GH_WORKFLOW_ACTOR: ${{ github.actor }}
      #   run: |
      #     git config user.email "${{ github.actor }}@users.noreply.github.com"
      #     git config user.name "${{ github.actor }}"
      #     ./_tools/release/02_create_pr.ts
